2024-10-11 01:39:00,441 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:384]
2024-10-11 01:39:04,841 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:384]
2024-10-11 01:39:13,788 INFO: Iniciando consulta al asistente [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:949]
2024-10-11 01:39:16,490 INFO: Iniciando consulta al asistente [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:949]
2024-10-11 01:39:16,491 INFO: Generando archivos [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:954]
2024-10-11 01:39:16,491 INFO: Iniciando generación de archivos [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:964]
2024-10-11 01:39:16,492 INFO: Generando PDF [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:987]
2024-10-11 01:39:16,494 ERROR: Unhandled exception: name 'Paragraph' is not defined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:476]
2024-10-11 02:15:23,345 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:346]
2024-10-11 02:18:21,348 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:346]
2024-10-11 02:18:47,683 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:346]
2024-10-11 02:21:28,938 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:346]
2024-10-11 02:23:28,241 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:348]
2024-10-11 10:50:03,657 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:348]
2024-10-11 10:50:05,873 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:348]
2024-10-11 11:53:10,432 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:348]
2024-10-11 11:55:52,707 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:378]
2024-10-11 12:01:05,453 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:378]
2024-10-11 12:05:21,013 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-11 12:48:13,907 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-11 12:49:54,825 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-11 13:23:53,378 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-11 13:23:57,044 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-11 13:32:01,224 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-11 13:32:04,338 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-11 13:52:43,418 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:52:43,427 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:52:43,427 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:53:21,434 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:53:21,437 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:53:21,445 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:56:04,993 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:56:05,000 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:56:05,005 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:56:05,045 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:56:05,059 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 13:56:05,061 ERROR: Unhandled exception: 429 Too Many Requests: 50 per 1 hour [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 22:47:45,236 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 23:38:48,556 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 23:39:17,593 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-11 23:48:33,155 ERROR: Unhandled exception: 'pagination' is undefined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:470]
2024-10-12 16:52:41,130 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-12 16:57:01,251 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-12 16:57:30,292 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:380]
2024-10-12 17:05:28,249 ERROR: Error al obtener categorías: name 'distinct' is not defined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:228]
