2024-10-24 12:04:34,010 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:04:37,129 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:04:41,205 ERROR: Unhandled exception: Error creating backref 'items_factura' on relationship 'ItemFactura.item': property of that name exists on mapper 'Mapper[InventarioItem(items_inventario)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:17:39,243 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:17:44,676 ERROR: Unhandled exception: Multiple classes found for path "MovimientoInventario" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:18:47,626 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:18:54,613 ERROR: Unhandled exception: Multiple classes found for path "ItemFactura" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:19:36,856 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:19:43,971 ERROR: Unhandled exception: Multiple classes found for path "ItemFactura" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:22:17,196 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:23:14,422 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:23:17,648 ERROR: Unhandled exception: Multiple classes found for path "ItemFactura" in the registry of this declarative base. Please use a fully module-qualified path. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:24:08,518 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:26:54,018 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:27:04,767 ERROR: Unhandled exception: Error creating backref 'items_facturas' on relationship 'ItemFactura.item': property of that name exists on mapper 'Mapper[InventarioItem(items_inventario)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:28:24,963 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:28:26,133 ERROR: Unhandled exception: Error creating backref 'items_facturas' on relationship 'ItemFactura.item': property of that name exists on mapper 'Mapper[InventarioItem(items_inventario)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:29:34,692 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:29:43,551 ERROR: Unhandled exception: Error creating backref 'factura' on relationship 'Facturacion.items': property of that name exists on mapper 'Mapper[ItemFactura(items_facturas)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:35:16,452 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:35:35,054 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:35:38,031 ERROR: Unhandled exception: Error creating backref 'item' on relationship 'InventarioItem.items_pre_factura': property of that name exists on mapper 'Mapper[ItemPreFactura(items_pre_factura)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:475]
2024-10-24 12:36:40,563 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:37:20,902 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 12:38:01,083 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:382]
2024-10-24 16:35:28,646 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:316]
2024-10-24 16:37:02,412 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\inventario\inventario_routes.py:316]
