2024-10-05 22:59:29,617 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-05 22:59:30,593 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-05 23:05:06,868 ERROR: Unhandled exception: facturacion/base_facturacion.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-05 23:09:33,698 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-05 23:24:48,684 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-05 23:25:08,600 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-05 23:34:04,370 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-05 23:35:31,827 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-05 23:35:36,008 ERROR: Unhandled exception: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-05 23:39:18,543 ERROR: Unhandled exception: facturacion/base_facturacion.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-05 23:46:18,581 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-05 23:47:04,525 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-05 23:47:05,298 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-05 23:47:48,763 ERROR: Unhandled exception: facturacion/base_facturacion.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-05 23:56:51,260 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-05 23:57:17,242 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 00:29:30,363 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 00:29:31,264 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 00:31:38,335 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:07:44,212 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:07:45,141 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:08:34,212 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:08:42,065 ERROR: Unhandled exception: Could not determine join condition between parent/child tables on relationship GestionClientes.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:08:49,855 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[GestionClientes(gestion_clientes)]'. Original exception was: Could not determine join condition between parent/child tables on relationship GestionClientes.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:09:02,696 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[GestionClientes(gestion_clientes)]'. Original exception was: Could not determine join condition between parent/child tables on relationship GestionClientes.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:09:17,332 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:14:42,121 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:14:43,208 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:14:46,792 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:16:59,973 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:17:07,558 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:17:15,885 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:17:44,516 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:17:45,566 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:20:48,107 ERROR: Unhandled exception: Could not determine join condition between parent/child tables on relationship Facturacion.cliente - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:20:53,099 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Facturacion(facturacion)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Facturacion.cliente - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:21:01,050 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Facturacion(facturacion)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Facturacion.cliente - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:23:12,134 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:23:18,494 ERROR: Unhandled exception: Error creating backref 'facturas' on relationship 'Facturacion.cliente': property of that name exists on mapper 'Mapper[Cliente(clientes)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:23:24,304 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Facturacion(facturacion)]'. Original exception was: Error creating backref 'facturas' on relationship 'Facturacion.cliente': property of that name exists on mapper 'Mapper[Cliente(clientes)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:24:15,058 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:24:16,759 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:24:30,314 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:24:31,137 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:24:43,489 ERROR: Unhandled exception: Error creating backref 'facturas' on relationship 'Facturacion.cliente': property of that name exists on mapper 'Mapper[Cliente(clientes)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:24:52,762 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Facturacion(facturacion)]'. Original exception was: Error creating backref 'facturas' on relationship 'Facturacion.cliente': property of that name exists on mapper 'Mapper[Cliente(clientes)]' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:309]
2024-10-06 01:29:06,676 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:29:07,505 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:29:45,911 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:35:23,590 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-06 01:35:55,239 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
