2024-09-27 17:40:50,797 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 17:40:52,646 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 17:40:56,630 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 17:45:09,428 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 17:49:46,025 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 17:49:47,407 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 17:49:56,705 ERROR: Error al cargar la página de bancos: (psycopg2.errors.UndefinedColumn) no existe la columna banco.fecha_creacion
LINE 1: ...elefono_contacto, banco.estatus AS banco_estatus, banco.fech...
                                                             ^

[SQL: SELECT banco.id AS banco_id, banco.nombre AS banco_nombre, banco.telefono AS banco_telefono, banco.contacto AS banco_contacto, banco.telefono_contacto AS banco_telefono_contacto, banco.estatus AS banco_estatus, banco.fecha_creacion AS banco_fecha_creacion, banco.fecha_actualizacion AS banco_fecha_actualizacion 
FROM banco]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\banco\routes.py:20]
2024-09-27 17:50:12,809 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:313]
2024-09-27 17:50:14,962 ERROR: Error al cargar la página de bancos: (psycopg2.errors.UndefinedColumn) no existe la columna banco.fecha_creacion
LINE 1: ...elefono_contacto, banco.estatus AS banco_estatus, banco.fech...
                                                             ^

[SQL: SELECT banco.id AS banco_id, banco.nombre AS banco_nombre, banco.telefono AS banco_telefono, banco.contacto AS banco_contacto, banco.telefono_contacto AS banco_telefono_contacto, banco.estatus AS banco_estatus, banco.fecha_creacion AS banco_fecha_creacion, banco.fecha_actualizacion AS banco_fecha_actualizacion 
FROM banco]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\banco\routes.py:20]
2024-09-27 20:59:30,710 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 20:59:45,469 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 21:00:00,954 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 21:07:13,468 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 21:09:42,447 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 21:09:45,361 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 21:11:43,692 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 21:12:29,986 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-27 23:07:30,117 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:08:16,146 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:09:31,762 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:09:49,246 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:09:59,241 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:11:49,936 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:16:37,281 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:17:04,958 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:17:06,456 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:17:12,775 ERROR: Unhandled exception: name 'Usuario' is not defined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:307]
2024-09-27 23:17:19,263 ERROR: Unhandled exception: name 'Usuario' is not defined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:307]
2024-09-27 23:17:29,453 ERROR: Unhandled exception: name 'Usuario' is not defined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:307]
2024-09-27 23:18:06,324 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:24:38,730 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:25:35,419 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:26:11,846 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:26:32,518 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:26:52,842 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:26:54,136 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:52]
2024-09-27 23:27:00,368 ERROR: Unhandled exception: name 'Usuario' is not defined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:307]
2024-09-27 23:27:02,870 ERROR: Unhandled exception: name 'Usuario' is not defined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:307]
2024-09-27 23:27:03,967 ERROR: Unhandled exception: name 'Usuario' is not defined [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:307]
2024-09-28 09:55:17,622 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-28 09:55:22,070 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-28 09:55:34,840 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-28 09:56:15,026 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-28 09:56:37,040 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-28 09:56:47,279 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:53]
2024-09-28 10:01:31,154 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:55]
2024-09-28 10:01:46,848 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:55]
2024-09-28 10:03:45,919 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:55]
2024-09-28 10:03:47,205 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:55]
2024-09-28 10:07:44,101 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:55]
2024-09-28 10:10:11,803 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:312]
2024-09-28 10:11:43,445 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:312]
2024-09-28 10:12:24,400 ERROR: Rol no encontrado: 'usuario' [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\admin_routes.py:189]
2024-09-28 10:12:36,518 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:312]
2024-09-28 10:12:40,267 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:312]
2024-09-28 10:12:40,307 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:312]
2024-09-28 10:12:40,337 INFO: Búsqueda de bancos realizada. Resultados: 1 [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\banco\routes.py:97]
2024-09-28 10:12:56,877 INFO: Búsqueda de bancos realizada. Resultados: 2 [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\banco\routes.py:97]
2024-09-28 10:13:01,628 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:312]
2024-09-28 10:13:01,637 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:312]
2024-09-28 10:13:01,659 INFO: Búsqueda de bancos realizada. Resultados: 2 [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\banco\routes.py:97]
2024-09-28 10:13:30,469 ERROR: Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:312]
