2024-11-20 22:52:26,778 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-20 22:52:35,599 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-20 22:52:41,962 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[TiendaFactura(tiendafactura)]'. Original exception was: Could not determine join condition between parent/child tables on relationship TiendaFactura.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:701]
2024-11-20 23:00:01,642 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-20 23:01:03,055 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Tienda(tiendas)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Tienda.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:701]
2024-11-21 11:33:14,712 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Tienda(tiendas)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Tienda.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:701]
2024-11-21 11:33:20,869 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Tienda(tiendas)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Tienda.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:701]
2024-11-21 11:36:30,444 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 11:36:33,824 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Tienda(tiendas)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Tienda.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:701]
2024-11-21 11:41:18,386 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 11:42:25,259 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 11:42:34,891 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Tienda(tiendas)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Tienda.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:701]
2024-11-21 11:42:52,837 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Tienda(tiendas)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Tienda.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:701]
2024-11-21 11:44:48,668 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 11:45:14,492 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 11:45:21,234 ERROR: Unhandled exception: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Tienda(tiendas)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Tienda.facturas - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:701]
2024-11-21 11:48:41,878 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 11:48:50,436 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 11:49:24,430 ERROR: Error creando tienda: (psycopg2.errors.UniqueViolation) llave duplicada viola restricción de unicidad «tiendafactura_codigo_key»
DETAIL:  Ya existe la llave (codigo)=(CB0008).

[SQL: INSERT INTO tiendafactura (codigo, nombre, direccion, telefono, email, moneda, activa, fecha_actualizacion) VALUES (%(codigo)s, %(nombre)s, %(direccion)s, %(telefono)s, %(email)s, %(moneda)s, %(activa)s, %(fecha_actualizacion)s) RETURNING tiendafactura.id, tiendafactura.fecha_creacion]
[parameters: {'codigo': 'CB0008', 'nombre': 'Prueba', 'direccion': 'allill33', 'telefono': '2396333330', 'email': 'el_renyk_rmg@hotmail.com', 'moneda': 'DOP', 'activa': True, 'fecha_actualizacion': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\facturas\facturacion_routes.py:454]
2024-11-21 11:51:51,328 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 11:54:28,146 ERROR: Error creando tienda: (builtins.TypeError) Not a boolean value: 'on'
[SQL: INSERT INTO tiendafactura (codigo, nombre, direccion, telefono, email, moneda, activa, fecha_actualizacion) VALUES (%(codigo)s, %(nombre)s, %(direccion)s, %(telefono)s, %(email)s, %(moneda)s, %(activa)s, %(fecha_actualizacion)s) RETURNING tiendafactura.id, tiendafactura.fecha_creacion]
[parameters: [{'nombre': 'Prueba', 'codigo': 'CB0009', 'telefono': '2396333330', 'moneda': 'DOP', 'email': 'el_renyk_rmg@hotmail.com', 'direccion': 'allill33', 'activa': 'on', 'fecha_actualizacion': None}]] [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\facturas\facturacion_routes.py:466]
2024-11-21 12:00:42,325 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 12:01:15,334 ERROR: Error creando tienda: (psycopg2.errors.UniqueViolation) llave duplicada viola restricción de unicidad «tiendafactura_codigo_key»
DETAIL:  Ya existe la llave (codigo)=(CB0010).

[SQL: INSERT INTO tiendafactura (codigo, nombre, direccion, telefono, email, moneda, activa, fecha_actualizacion) VALUES (%(codigo)s, %(nombre)s, %(direccion)s, %(telefono)s, %(email)s, %(moneda)s, %(activa)s, %(fecha_actualizacion)s) RETURNING tiendafactura.id, tiendafactura.fecha_creacion]
[parameters: {'codigo': 'CB0010', 'nombre': 'Prueba', 'direccion': 'allill33', 'telefono': '2396333330', 'email': 'el_renyk_rmg@hotmail.com', 'moneda': 'DOP', 'activa': True, 'fecha_actualizacion': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\facturas\facturacion_routes.py:444]
2024-11-21 12:04:09,628 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 12:11:10,172 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 12:11:59,299 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 12:14:30,911 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 12:17:03,243 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 12:17:34,288 ERROR: Error creando tienda: (psycopg2.errors.UniqueViolation) llave duplicada viola restricción de unicidad «tiendafactura_codigo_key»
DETAIL:  Ya existe la llave (codigo)=(CB0021).

[SQL: INSERT INTO tiendafactura (codigo, nombre, direccion, telefono, email, moneda, activa, fecha_actualizacion) VALUES (%(codigo)s, %(nombre)s, %(direccion)s, %(telefono)s, %(email)s, %(moneda)s, %(activa)s, %(fecha_actualizacion)s) RETURNING tiendafactura.id, tiendafactura.fecha_creacion]
[parameters: {'codigo': 'CB0021', 'nombre': 'Prueba', 'direccion': 'allill33', 'telefono': '2396333330', 'email': 'el_renyk_rmg@hotmail.com', 'moneda': 'USD', 'activa': True, 'fecha_actualizacion': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\facturas\facturacion_routes.py:469]
2024-11-21 12:19:32,166 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 12:32:09,604 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
2024-11-21 12:32:38,787 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:594]
