2024-10-03 22:32:23,235 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-03 22:32:24,099 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-03 22:39:59,581 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-03 22:41:21,042 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-03 22:41:27,585 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-03 23:37:11,550 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-03 23:45:56,996 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-03 23:45:57,797 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:260]
2024-10-03 23:46:27,148 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-03 23:49:23,310 ERROR: Unhandled exception: (psycopg2.errors.UndefinedColumn) no existe la columna factura.total
LINE 1: ..._fecha, factura.cliente_id AS factura_cliente_id, factura.to...
                                                             ^

[SQL: SELECT factura.id AS factura_id, factura.numero AS factura_numero, factura.fecha AS factura_fecha, factura.cliente_id AS factura_cliente_id, factura.total AS factura_total, factura.estado AS factura_estado 
FROM factura]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-03 23:53:46,649 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 00:35:42,095 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 00:35:42,867 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 00:36:06,750 ERROR: Unhandled exception: (psycopg2.errors.UndefinedColumn) no existe la columna factura.total
LINE 1: ..._fecha, factura.cliente_id AS factura_cliente_id, factura.to...
                                                             ^

[SQL: SELECT factura.id AS factura_id, factura.numero AS factura_numero, factura.fecha AS factura_fecha, factura.cliente_id AS factura_cliente_id, factura.total AS factura_total, factura.estado AS factura_estado 
FROM factura]
(Background on this error at: https://sqlalche.me/e/20/f405) [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 00:50:31,244 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 01:05:53,984 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 01:05:54,865 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 08:56:45,592 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:00:14,842 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:01:14,200 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:01:23,597 INFO: Accediendo a la ruta de facturación [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:832]
2024-10-04 09:02:14,714 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:02:23,907 INFO: Accediendo a la ruta de facturación [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:832]
2024-10-04 09:11:25,465 INFO: Accediendo a la ruta de facturación [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:832]
2024-10-04 09:15:47,938 INFO: Accediendo a la ruta de facturación [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:832]
2024-10-04 09:19:17,013 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:19:17,939 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:22:59,960 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:23:00,849 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:24:35,840 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:24:50,450 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:25:22,981 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:35:32,494 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:35:33,431 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:35:50,412 ERROR: Unhandled exception: facturacion_facturas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 09:40:12,127 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:44:56,816 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:44:57,659 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:55:00,974 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:57:28,034 ERROR: Unhandled exception: facturacion/index.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 09:58:21,581 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:59:24,132 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 09:59:25,060 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:03:27,560 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:04:57,016 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:04:57,912 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:48:09,647 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:49:02,967 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:49:03,860 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:49:21,469 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:51:51,692 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:54:28,236 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 10:54:29,127 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 16:03:15,216 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 16:04:00,536 ERROR: Unhandled exception: facturacion/facturas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 16:04:29,392 ERROR: Unhandled exception: facturacion/facturas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 16:06:25,549 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 16:09:09,493 ERROR: Unhandled exception: facturacion/facturas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 16:09:19,441 ERROR: Unhandled exception: facturacion/facturas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 16:09:24,986 ERROR: Unhandled exception: facturacion/facturas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 16:09:33,206 ERROR: Unhandled exception: facturacion/facturas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 16:12:34,544 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 16:12:50,385 INFO: Solicitud recibida para Facturacion - Facturas [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:832]
2024-10-04 16:12:50,391 ERROR: Error al procesar la solicitud: facturacion/facturas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:840]
2024-10-04 16:13:09,017 INFO: Solicitud recibida para Facturacion - Facturas [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:832]
2024-10-04 16:13:09,017 ERROR: Error al procesar la solicitud: facturacion/facturas.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:840]
2024-10-04 16:24:45,066 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 16:30:39,786 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 16:31:12,626 INFO: Accediendo a la ruta de facturación [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:832]
2024-10-04 16:31:12,628 ERROR: Unhandled exception: facturacion/index.html [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:311]
2024-10-04 16:42:38,839 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 18:55:02,522 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
2024-10-04 19:16:38,489 INFO: CalculAI startup [in C:\Users\el_re\OneDrive - Sendiu\Desktop\CalculAI\ERP\app.py:261]
